In [3]:
import pandas as pd
dvf = pd.read_csv("../data/bronze/dvf.csv")
insee = pd.read_csv("../data/bronze/insee.csv", sep=";")

C:\Users\user\AppData\Local\Temp\ipykernel_12420\1773790743.py:2: DtypeWarning: Columns (2,4,5,9,10,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,28,29,31,32,35,36,37,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  dvf = pd.read_csv("../data/bronze/dvf.csv")

Nous chargeons les données brutes depuis la couche Bronze.

In [4]:
dvf.head()

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
0,2025-1273241,2025-01-03,1,Vente,1500000.0,27.0,NaN,RUE DES ROSIERS,8370,75004.0,...,160.0,0.0,NaN,NaN,NaN,NaN,NaN,2.358325,48.857555,000AJ
1,2025-1273242,2025-01-03,1,Vente,430500.0,88.0,NaN,RUE MARCADET,5995,75018.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2.346344,48.890689,000BJ
2,2025-1273242,2025-01-03,1,Vente,430500.0,88.0,NaN,RUE MARCADET,5995,75018.0,...,48.0,3.0,NaN,NaN,NaN,NaN,NaN,2.346344,48.890689,000BJ
3,2025-1273243,2025-01-03,1,Vente,527700.0,161.0,NaN,RUE MARCADET,5995,75018.0,...,40.0,1.0,NaN,NaN,NaN,NaN,NaN,2.337299,48.891073,000AV
4,2025-1273243,2025-01-03,1,Vente,527700.0,161.0,NaN,RUE MARCADET,5995,75018.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2.337299,48.891073,000AV

In [5]:
insee.head()

,CODGEO,NBMENFISC17,NBPERSMENFISC17,MED17,PIMP17,TP6017,TP60AGE117,TP60AGE217,TP60AGE317,TP60AGE417,...,PPEN17,PPAT17,PPSOC17,PPFAM17,PPMINI17,PPLOGT17,PIMPOT17,D117,D917,RD17
0,011,50816,119613,21870,53.3,10.4,14.9,11.7,11.8,10.0,...,27.8,8.4,4.6,2.3,1.3,1.0,-15.1,12540,35950,2.9
1,012,134811,327215,22480,56.2,8.7,13.8,10.1,9.9,8.3,...,27.1,9.6,4.3,2.3,1.1,0.9,-16.0,13170,37230,2.8
2,013,33183,80899,34520,52.5,13.0,14.5,11.8,13.7,15.8,...,17.9,7.9,1.3,0.5,0.4,0.4,-17.9,10640,77950,7.3
3,014,37860,91351,20480,49.0,15.2,18.9,19.2,17.7,14.0,...,26.1,8.3,5.3,2.5,1.5,1.3,-14.7,11160,36570,3.3
4,021,28533,68867,20290,50.8,14.3,22.1,17.3,16.4,15.0,...,28.0,9.9,5.8,2.7,1.8,1.3,-15.8,11250,33890,3.0

Nous affichons les premières lignes afin de comprendre la structure générale des datasets.

In [6]:
dvf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420066 entries, 0 to 420065
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id_mutation                   420066 non-null  object
 1   date_mutation                 420066 non-null  object
 2   numero_disposition            420066 non-null  object
 3   nature_mutation               420066 non-null  object
 4   valeur_fonciere               413590 non-null  object
 5   adresse_numero                418544 non-null  object
 6   adresse_suffixe               18160 non-null   object
 7   adresse_nom_voie              418595 non-null  object
 8   adresse_code_voie             418595 non-null  object
 9   code_postal                   418588 non-null  object
 10  code_commune                  420066 non-null  object
 11  nom_commune                   420066 non-null  object
 12  code_departement              420066 non-null  object
 13  ancien_code_commune           8 non-null       object
 14  ancien_nom_commune            8 non-null       object
 15  id_parcelle                   420066 non-null  object
 16  ancien_id_parcelle            8 non-null       object
 17  numero_volume                 1428 non-null    object
 18  lot1_numero                   377665 non-null  object
 19  lot1_surface_carrez           160430 non-null  object
 20  lot2_numero                   179943 non-null  object
 21  lot2_surface_carrez           49223 non-null   object
 22  lot3_numero                   29907 non-null   object
 23  lot3_surface_carrez           5001 non-null    object
 24  lot4_numero                   10938 non-null   object
 25  lot4_surface_carrez           1193 non-null    object
 26  lot5_numero                   4579 non-null    object
 27  lot5_surface_carrez           449 non-null     object
 28  nombre_lots                   420066 non-null  object
 29  code_type_local               415933 non-null  object
 30  type_local                    415933 non-null  object
 31  surface_reelle_bati           215370 non-null  object
 32  nombre_pieces_principales     415885 non-null  object
 33  code_nature_culture           40966 non-null   object
 34  nature_culture                40966 non-null   object
 35  code_nature_culture_speciale  743 non-null     object
 36  nature_culture_speciale       743 non-null     object
 37  surface_terrain               40638 non-null   object
 38  longitude                     419405 non-null  object
 39  latitude                      419405 non-null  object
 40  section_prefixe               420066 non-null  object
dtypes: object(41)
memory usage: 131.4+ MB

In [7]:
insee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328 entries, 0 to 327
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CODGEO           328 non-null    object
 1   NBMENFISC17      328 non-null    int64
 2   NBPERSMENFISC17  328 non-null    int64
 3   MED17            328 non-null    int64
 4   PIMP17           328 non-null    float64
 5   TP6017           328 non-null    float64
 6   TP60AGE117       325 non-null    float64
 7   TP60AGE217       328 non-null    float64
 8   TP60AGE317       328 non-null    float64
 9   TP60AGE417       328 non-null    float64
 10  TP60AGE517       328 non-null    float64
 11  TP60AGE617       326 non-null    float64
 12  TP60TOL117       328 non-null    float64
 13  TP60TOL217       328 non-null    float64
 14  PACT17           328 non-null    float64
 15  PTSA17           328 non-null    float64
 16  PCHO17           328 non-null    float64
 17  PBEN17           328 non-null    float64
 18  PPEN17           328 non-null    float64
 19  PPAT17           328 non-null    float64
 20  PPSOC17          328 non-null    float64
 21  PPFAM17          328 non-null    float64
 22  PPMINI17         328 non-null    float64
 23  PPLOGT17         328 non-null    float64
 24  PIMPOT17         328 non-null    float64
 25  D117             328 non-null    int64
 26  D917             328 non-null    int64
 27  RD17             328 non-null    float64
dtypes: float64(22), int64(5), object(1)
memory usage: 71.9+ KB

Nous examinons les colonnes, les types de données et la taille des datasets.

In [8]:
dvf.describe()

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
count,420066,420066,420066,420066,413590.0,418544.0,18160,418595,418595,418588.0,...,215370.0,415885.0,40966,40966,743,743,40638.0,419405.000000,419405.000000,420066
unique,156809,1426,15,7,41942.0,763.0,14,3938,3870,41.0,...,1749.0,40.0,5,5,4,4,1238.0,54293.000000,49173.000000,160
top,2022-1671153,2022-04-19,1,Vente,300000.0,6.0,B,RUE DE VAUGIRARD,9624,75015.0,...,30.0,0.0,S,sols,IMM,Dépendances d'ensemble immobilier,5508.0,2.342517,48.822767,000AR
freq,2964,3424,286743,412954,1714.0,8049.0,14281,3258,3258,42398.0,...,3796.0,157024.0,40012,40012,727,727,1020.0,1020.000000,1020.000000,7634

Nous analysons les distributions des variables numériques.

In [9]:
dvf.isnull().sum()

id_mutation                          0
date_mutation                        0
numero_disposition                   0
nature_mutation                      0
valeur_fonciere                   6476
adresse_numero                    1522
adresse_suffixe                 401906
adresse_nom_voie                  1471
adresse_code_voie                 1471
code_postal                       1478
code_commune                         0
nom_commune                          0
code_departement                     0
ancien_code_commune             420058
ancien_nom_commune              420058
id_parcelle                          0
ancien_id_parcelle              420058
numero_volume                   418638
lot1_numero                      42401
lot1_surface_carrez             259636
lot2_numero                     240123
lot2_surface_carrez             370843
lot3_numero                     390159
lot3_surface_carrez             415065
lot4_numero                     409128
lot4_surface_carrez             418873
lot5_numero                     415487
lot5_surface_carrez             419617
nombre_lots                          0
code_type_local                   4133
type_local                        4133
surface_reelle_bati             204696
nombre_pieces_principales         4181
code_nature_culture             379100
nature_culture                  379100
code_nature_culture_speciale    419323
nature_culture_speciale         419323
surface_terrain                 379428
longitude                          661
latitude                           661
section_prefixe                      0
dtype: int64

In [10]:
insee.isnull().sum()

CODGEO             0
NBMENFISC17        0
NBPERSMENFISC17    0
MED17              0
PIMP17             0
TP6017             0
TP60AGE117         3
TP60AGE217         0
TP60AGE317         0
TP60AGE417         0
TP60AGE517         0
TP60AGE617         2
TP60TOL117         0
TP60TOL217         0
PACT17             0
PTSA17             0
PCHO17             0
PBEN17             0
PPEN17             0
PPAT17             0
PPSOC17            0
PPFAM17            0
PPMINI17           0
PPLOGT17           0
PIMPOT17           0
D117               0
D917               0
RD17               0
dtype: int64

Nous identifions les colonnes contenant des valeurs nulles afin de préparer le nettoyage.

In [11]:
dvf[["valeur_fonciere", "surface_reelle_bati"]].describe()

        valeur_fonciere  surface_reelle_bati
count          413590.0             215370.0
unique          41942.0               1749.0
top            300000.0                 30.0
freq             1714.0               3796.0

Nous nous concentrons sur les variables importantes : prix, surface et localisation.

In [12]:
insee[["MED17"]].describe()

              MED17
count    328.000000
mean   20546.189024
std     2140.842625
min    13350.000000
25%    19515.000000
50%    20220.000000
75%    21167.500000
max    34520.000000

Nous examinons la variable de revenu médian par arrondissement.

Cette phase d’exploration nous a permis de :

- Identifier les variables pertinentes pour chaque dataset
- Détecter la présence de valeurs manquantes
- Comprendre la structure des données

Ces observations serviront de base pour les étapes de nettoyage et de transformation (Silver).